version: '{build}'
image: Visual Studio 2019
configuration: Release
init:
- pwsh: >-
    if ($env:APPVEYOR_REPO_TAG -eq "true")
    {
        Update-AppveyorBuild -Version "$($env:APPVEYOR_REPO_TAG_NAME.TrimStart("v"))"
    }
    else
    {
        Update-AppveyorBuild -Version "0.0.1+dev-$($env:APPVEYOR_REPO_COMMIT.Substring(0, 7))"
    }    
dotnet_csproj:
  patch: true
  file: '**\*.csproj;**\*.props'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
before_build:
- ps: >-
    nuget restore Nemesis.Essentials.sln

    if ($env:APPVEYOR_REPO_TAG_NAME)
    {
        $releaseNotes = .\GetGithubReleaseNotes.ps1 -tagName "$env:APPVEYOR_REPO_TAG_NAME" -repoOwner "nemesissoft" -repoName "Nemesis.Essentials"

        if($releaseNotes)
        {
            Update-AppveyorBuild -Message "$releaseNotes"

            .\UpdateReleaseNotes.ps1 -basePath "$env:APPVEYOR_BUILD_FOLDER" -releaseNotes "$releaseNotes"
        }        
    }       

build:
  project: Nemesis.Essentials.sln
  verbosity: normal
artifacts:
- path: '**\*.nupkg'
  name: NuGet Packages
- path: '**\*.snupkg'
  name: NuGet Symbols Packages
deploy:
- provider: NuGet
  api_key:
    secure: vd8yW7QMjs4O+Bp1KjU5JOp0+MteVsroKNGz6h+/mjG4SVpBRPq7tK37deBj6FDD
  on:
    branch: master
    APPVEYOR_REPO_TAG: true